[mic]
driver = "alsa"
device_name = "hw:seeed8micvoicec"
sample_rate = 16000
period = 16
n_channel = 8

[audio_connection]
connect_mic_speaker = false
mic_idx = 0
speaker_idx = 0

[tcp]
listen_port = 2345
max_clients = 10
